### ISSUE TITLE
Bundle natives in AAR

### ISSUE THREAD

**Issue by barsoosayque** [barsoosayque/libgdx-oboe#2]
As it was before 0.2.2 version, it should be possible for users to define only one dependency on libgdx-oboe (without using the `natives` configuration). This should work out of the box, and it also worked before.

**Comment by la-matthew-yang** [comment]
How does this work? Does the aar file include all the native libraries? As of 0.2.3, only the .so files of the correct abi filters are packaged into apk. Will that stay the same?

**Comment by barsoosayque** [comment]
> Does the aar file include all the native libraries?

Yep.

> As of 0.2.3, only the .so files of the correct abi filters are packaged into apk. Will that stay the same?

I believe so. AAR is basically an archive, so it should not affect build artifacts (such as apk).

**Comment by barsoosayque** [comment]
Should be fixed starting from [v0.2.4](../releases/tag/v0.2.4).

**Comment by la-matthew-yang** [comment]
I have tried it and everything is working as intended. Can this same process be applied to libgdx native libraries as well?  I don't see why it can't. If this works, it can remove the need for libgdx native dependencies and the task copyAndroidNatives.

**Comment by barsoosayque** [comment]
Phew, I was worried it won't find libraries.
It can be done with libgdx natives as well, although, if I remember this correctly, they are keeping multiple jars for some compatibility reasons. It's fairly easy to migrate to aar.

**Comment by la-matthew-yang** [comment]
I see. That is good to know.
